/// <reference types="node" />

// The MIT License (MIT)
// 
// vs-deploy (https://github.com/mkloubert/vs-deploy)
// Copyright (c) Marcel Joachim Kloubert <marcel.kloubert@gmx.net>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

import * as deploy_contracts from './contracts';
import * as deploy_helpers from './helpers';
import * as OS from 'os';
import * as vs_deploy from './deploy';
import * as vscode from 'vscode';


/**
 * A basic value.
 */
export abstract class ValueBase implements deploy_contracts.ObjectWithNameAndValue {
    /**
     * Stores the underlying item.
     */
    protected readonly _ITEM: deploy_contracts.ValueWithName;

    /**
     * Initializes a new instance of that class.
     * 
     * @param {deploy_contracts.ValueWithName} [item] The underlying item.
     */
    constructor(item?: deploy_contracts.ValueWithName) {
        if (!item) {
            item = {
                name: undefined,
                type: undefined,
            };
        }
        
        this._ITEM = item;
    }

    /**
     * Gets the underlying item.
     */
    public get item(): deploy_contracts.ValueWithName {
        return this._ITEM;
    }

    /** @inheritdoc */
    public get name(): string {
        return this.item.name;
    }

    /** @inheritdoc */
    public abstract get value(): any;
}

/**
 * A value generated by (JavaScript) code.
 */
export class CodeValue extends ValueBase {
    /** @inheritdoc */
    constructor(value?: deploy_contracts.CodeValueWithName) {
        super(value);
    }
    
    /** @inheritdoc */
    public get code(): string {
        return deploy_helpers.toStringSafe(this.item.code);
    }

    /**
     * Gets the underlying item.
     */
    public get item(): deploy_contracts.CodeValueWithName {
        return <deploy_contracts.CodeValueWithName>super.item;
    }

    /** @inheritdoc */
    public get value(): any {
        let $cwd = process.cwd();
        let $homeDir = OS.homedir();
        let $me = this;
        let $workspaceRoot = vscode.workspace.rootPath;

        return eval(this.code);
    }
}

/**
 * A value that accesses an environment variable.
 */
export class EnvValue extends ValueBase {
    /** @inheritdoc */
    constructor(value?: deploy_contracts.EnvValueWithName) {
        super(value);
    }

    /** @inheritdoc */
    public get alias(): string {
        return this.item.alias;
    }

    /** @inheritdoc */
    public get name(): string {
        return deploy_helpers.isEmptyString(this.alias) ? this.realName
                                                        : this.alias;
    }

    /**
     * Gets the underlying item.
     */
    public get item(): deploy_contracts.EnvValueWithName {
        return <deploy_contracts.EnvValueWithName>super.item;
    }

    /** @inheritdoc */
    public get value(): any {
        let value: any;

        let myName = deploy_helpers.toStringSafe(this.realName).trim();

        for (let p in process.env) {
            if (deploy_helpers.toStringSafe(p).trim() === myName) {
                value = process.env[p];  // found
                break;
            }
        }

        return value;
    }

    /**
     * Gets the "real" name.
     */
    public get realName(): string {
        return super.name;
    }
}

/**
 * A static value.
 */
export class StaticValue extends ValueBase {
    /** @inheritdoc */
    constructor(value?: deploy_contracts.StaticValueWithName) {
        super(value);
    }

    /**
     * Gets the underlying item.
     */
    public get item(): deploy_contracts.StaticValueWithName {
        return <deploy_contracts.StaticValueWithName>super.item;
    }

    /** @inheritdoc */
    public get value(): any {
        return this.item.value;
    }
}

/**
 * Gets the current list of values.
 * 
 * @return {ValueBase[]} The values.
 */
export function getValues(): ValueBase[] {
    let me: vs_deploy.Deployer = this;

    let myName = me.name;

    let values = deploy_helpers.asArray(me.config.values)
                               .filter(x => x);

    // isFor
    values = values.filter(v => {
        let validHosts = deploy_helpers.asArray(v.isFor)
                                       .map(x => deploy_helpers.normalizeString(x))
                                       .filter(x => '' !== x);

        if (validHosts.length < 1) {
            return true;
        }

        return validHosts.indexOf(myName) > -1;
    });

    // platforms
    values = deploy_helpers.filterPlatformItems(values);

    let objs = toValueObjects(values);

    // ${cwd}
    {
        objs.push(new CodeValue({
            name: 'cwd',
            type: "code",
            code: "process.cwd()",
        }));
    }

    // ${homeDir}
    {
        objs.push(new CodeValue({
            name: 'homeDir',
            type: "code",
            code: "require('os').homedir()",
        }));
    }

    // ${workspaceRoot}
    {
        objs.push(new CodeValue({
            name: 'workspaceRoot',
            type: "code",
            code: "require('vscode').workspace.rootPath",
        }));
    }

    return objs;
}

/**
 * Converts a list of value items to objects.
 * 
 * @param {(deploy_contracts.ValueWithName|deploy_contracts.ValueWithName[])} items The item(s) to convert.
 *  
 * @returns {ValueBase[]} The items as objects. 
 */
export function toValueObjects(items: deploy_contracts.ValueWithName | deploy_contracts.ValueWithName[]): ValueBase[] {
    let result: ValueBase[] = [];

    deploy_helpers.asArray(items).filter(i => i).forEach(i => {
        let newValue: ValueBase;
        
        switch (deploy_helpers.normalizeString(i.type)) {
            case '':
            case 'static':
                newValue = new StaticValue(<deploy_contracts.StaticValueWithName>i);
                break;

            case 'code':
                newValue = new CodeValue(<deploy_contracts.CodeValueWithName>i);
                break;

            case 'env':
            case 'environment':
                newValue = new EnvValue(<deploy_contracts.EnvValueWithName>i);
                break;
        }

        if (newValue) {
            result.push(newValue);
        }
    });

    return result;
}
